worker_processes  1;

events{
    worker_connections  1024;
}

http {
    upstream booking_backend {
        # Primary server is the default
        server booking-primary:3002;
        # Backup server takes over only when primary is down
        server booking-backup:3002 backup;
    }

    server {
        listen 80;

        location /api/auth/ {
            rewrite ^/api/auth/(.*) /auth/$1 break;
            proxy_pass http://auth-service:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/booking/ {
            rewrite ^/api/booking/(.*) /$1 break;
            proxy_pass http://booking_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /client {
            return 301 $scheme://$http_host/;
        }

        location / {
            proxy_pass http://client:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
